// <autogenerated>
//   This file was generated by T4 code generator EntityCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

//------------------------------------------------------------------------------
//Copyright ©车易拍-公共服务组团队. All Rights Reserved.
//------------------------------------------------------------------------------
using System.ComponentModel.Composition;
using Component.Data;

namespace Core.Service.Impl
{
	/// <summary>
    ///     核心业务实现基类
    /// </summary>
    public abstract class CoreServiceBase
    {
        /// <summary>
        ///     获取或设置 工作单元对象，用于处理同步业务的事务操作
        /// </summary>
        [Import]
        protected IUnitOfWork UnitOfWork { get; set; }
    }
}
