// <autogenerated>
//   This file was generated by T4 code generator EntityCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System.Data.Entity;

namespace Component.Data
{
	public class DbSetEntity
	{
 
            public DbSet<Core.Models.Reports> Reports { get; set; }

            public DbSet<Core.Models.Sys_Functions> Sys_Functions { get; set; }

            public DbSet<Core.Models.Sys_Menu> Sys_Menu { get; set; }

            public DbSet<Core.Models.TestData> TestData { get; set; }
		
	}
}
