//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public int InspectorId { get; set; }
        public string TradeCode { get; set; }
        public string PlateNumber { get; set; }
        public string Country { get; set; }
        public string Brand { get; set; }
        public string Manufacturer { get; set; }
        public string Series { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Displacement { get; set; }
        public string Category { get; set; }
        public string DriveType { get; set; }
        public string Transmission { get; set; }
        public string Vin { get; set; }
        public string LicenseModel { get; set; }
        public Nullable<decimal> Mileage { get; set; }
        public string Engineserial { get; set; }
        public string VehicleType { get; set; }
        public string ExteriorColor { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> BuildDate { get; set; }
        public string AccidentData { get; set; }
        public string Score { get; set; }
        public string Detail { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
