//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Menu
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public int ModuleId { get; set; }
        public int FunId { get; set; }
        public string MenuName { get; set; }
        public string MenuDesc { get; set; }
        public string MenuImg { get; set; }
        public string LinkPage { get; set; }
        public Nullable<bool> IsMainMenu { get; set; }
        public Nullable<short> DisplayOrder { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
