//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Functions
    {
        public int Id { get; set; }
        public string FunName { get; set; }
        public string FunDesc { get; set; }
        public string FunCode { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string AllOperates { get; set; }
        public string DefaultOperates { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
